### ISSUE TITLE
Search engines may crawl website using a sitemap.xml file

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/zinc.coop#46]
Inspired by @colombene's usage of Figma to lay out where we're _headed_; I wonder if it makes sense for us to generate a [sitemap file](https://en.wikipedia.org/wiki/Sitemaps) that shows _where we are_ to search engines?

I don't really know how important this is from a web presence perspective; but it seems like a useful thing to know more about at the very least.

**Comment by anaulin** [comment]
My understanding is that the main benefit of a sitemap is to let a search engine know about pages (or even non-HTML files) on your site that might not be well-linked or otherwise not easily discoverable for a crawler. A canonical example that comes to mind (from my time at Google) is eBay autogenerating a sitemap with every single product for sale, to make sure those would show up in search results as fast as possible. 

For a smallish, straightforward site like the current zinc.coop, I'm not sure it's worth the trouble (Google, for one, appears to be defining "small site" as "about 500 pages or less on your site"). Doing a quick site search on Google, it seems all pages are already indexed anyway: https://www.google.com/search?q=site%3Azinc.coop

Here's Google's help page with rules of thumb of when a site might need a sitemap: https://support.google.com/webmasters/answer/156184?hl=en

**Comment by zspencer** [comment]
Thanks! Right now, the website doesn't really have an "owner" so it moves in fits and starts, and we haven't really figured out a way to identify and prioritize work on it.

I agree that for now, a sitemap.xml may not make a ton of sense. My goal with putting issues like this out there is so when someone is looking to dig into that particular aspect of computering they have some useful signposts; which I think you've helped quite a bit with, so [I've awarded you 20 patronage points for this contribution](https://airtable.com/tblndyi9VR3shxtmS/viwXhtTpHgcvWfNI9/recQEV70V3fwOLNyW)!
